pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: pipeline_postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: pipeline
      schema: marts
      threads: 1
